# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DataDefinedLabelImporter
                                 A QGIS plugin
 Helps you to import Labeldata, stored in an auxiliary Layer from another Project.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-10
        copyright            : (C) 2024 by Tobias
        email                : heitob903@outlook.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DataDefinedLabelImporter class from file DataDefinedLabelImporter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .label_importer import DataDefinedLabelImporter
    return DataDefinedLabelImporter(iface)
