# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DataDefinedLabelImporterDialog
                                 A QGIS plugin
 Helps you to import Labeldata, stored in an auxiliary Layer from another Project.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-10
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Tobias
        email                : heitob903@outlook.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.core import QgsProject, QgsMapLayer
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QApplication, QVBoxLayout, QWidget, QTreeWidget, QTreeWidgetItem

#from qgis.utils import iface
from label_importer.gui.layers_to_copy_widget import LayerToCopyWidget

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'label_importer_dialog_base.ui'))


class DataDefinedLabelImporterDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(DataDefinedLabelImporterDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.LayerToCopyWidget = LayerToCopyWidget()
        #self.iface = iface
        self.setupUi(self)
        self.setup_gui()



    def setup_gui(self):
        def set_up_combo_box():
            self.LayerToCopyWidget.treeWidget.clear()
            file_path = self.projectFile.filePath()
            self.project = QgsProject()
            self.project.read(file_path)
            layers = self.project.mapLayers().values()
            for layer in layers:
                if layer.type() == QgsMapLayer.VectorLayer:
                    if not layer.auxiliaryLayer() is None :
                        item = QTreeWidgetItem([layer.name()])
                #item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
               #item.setCheckState(0, Qt.Unchecked)
                        self.LayerToCopyWidget.treeWidget.addTopLevelItem(item)
        
        def validate_inputs():
            # Check if all required fields have values
            #if self.line_edit1.text().strip() and self.line_edit2.text().strip():
                self.button_box.setEnabled(True)
            #else:
            #    self.button_box.setEnabled(False)


        def activate_refresh_button():
            self.refreshButton.setEnabled(True)


        self.button_box.setEnabled(False)


        
        self.advancedOptionsGroupBox.layout().addWidget(self.LayerToCopyWidget)

        self.projectFile.fileChanged.connect(activate_refresh_button)
        self.projectFile.fileChanged.connect(validate_inputs)
            
            
        self.refreshButton.clicked.connect(lambda file_path: set_up_combo_box())
        #self.advancedOptionsGroupBox.layout().addWidget(self.dirsToCopyWidget)
